version: '3.9'
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${UNWEAVE_DB_USER}
      POSTGRES_PASSWORD: ${UNWEAVE_DB_PASSWORD}
      POSTGRES_DB: ${UNWEAVE_DB_NAME}
      POSTGRES_HOST: ${UNWEAVE_DB_HOST}
      POSTGRES_PORT: ${UNWEAVE_DB_PORT}
    healthcheck:
      test: pg_isready -U ${UNWEAVE_DB_USER} -d ${UNWEAVE_DB_NAME}
      interval: 2s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: dev

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      UNWEAVE_API_PORT: ${UNWEAVE_API_PORT}
      UNWEAVE_DB_USER: ${UNWEAVE_DB_USER}
      UNWEAVE_DB_PASSWORD: ${UNWEAVE_DB_PASSWORD}
      UNWEAVE_DB_NAME: ${UNWEAVE_DB_NAME}
      UNWEAVE_DB_HOST: db
      UNWEAVE_DB_PORT: ${UNWEAVE_DB_PORT}
    working_dir: /home/unweave
    volumes:
      - ./:/home/unweave
