version: '3'
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_SCHEMA: ${DB_SCHEMA}

  api:
    build: workbench
    ports:
      - "8000:8000"
    expose:
      - "8000"

  generate-spec:
    image: quay.io/goswagger/swagger
    working_dir: /home/unweave/
    volumes:
      - .:/home/unweave/
    entrypoint: "sh -c"
    command: ["swagger generate spec -o ./swagger.json && swagger validate ./swagger.json"]

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
