version: '3.9'

services:
  db:
    image: postgres:14.0
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unweavedbpwd_local
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"

  dbmate:
    image: ghcr.io/amacneil/dbmate:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
        DBMATE_DATABASE_URL: postgres://postgres:unweavedbpwd_local@db:5432/postgres
        DBMATE_MIGRATIONS_DIR: /docker-entrypoint-initdb.d/migrations
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d/migrations"
    command:
      - /bin/bash
      - -c
      - |
        dbmate migrate        
        dbmate dump
